module.exports = {
  presets: [
    {
      theme: {
        extend: {
          screens: {
            xs: "480px",
            sm: "640px",
            md: "768px",
            lg: "1024px",
            xl: "1216px"
          },
          colors: {
            transparent: "transparent",
            current: "currentColor",
            black: "#000",
            white: "#fff",
            gray: {
              50: "#F5FAF9",
              100: "#EDF2F1",
              200: "#D9DEDD",
              300: "#C7CFCD",
              400: "#AEB5B4",
              500: "#929C9A",
              600: "#7F8786",
              700: "#646A69",
              800: "#4C524F",
              900: "#1D1F1E"
            },
            orange: {
              50: "#FFFFFF",
              100: "#FFEDD5",
              200: "#FED7AA",
              300: "#FDBA74",
              400: "#FB923C",
              500: "#F97316",
              600: "#EA580C",
              700: "#C2410C",
              800: "#9A3412",
              900: "#7C2D12"
            },
            blue: {
              50: "#EFF6FF",
              100: "#DBEAFE",
              200: "#BFDBFE",
              300: "#BEF264",
              400: "#60A5FA",
              500: "#1C3F7C",
              600: "#2563EB",
              700: "#1D4ED8",
              800: "#1E40AF",
              900: "#0A172E"
            }
          },
          spacing: {
            0: "0px",
            1: "0.25rem",
            2: "0.5rem",
            3: "0.75rem",
            4: "1rem",
            5: "1.25rem",
            6: "1.5rem",
            7: "1.75rem",
            8: "2rem",
            9: "2.25rem",
            10: "2.5rem",
            11: "2.75rem",
            12: "3rem",
            14: "3.5rem",
            16: "4rem",
            18: "4.5rem",
            20: "5rem",
            24: "6rem",
            27: "6.75rem",
            28: "7rem",
            32: "8rem",
            34: "8.5rem",
            36: "9rem",
            40: "10rem",
            44: "11rem",
            48: "12rem",
            52: "13rem",
            56: "14rem",
            60: "15rem",
            62: "15.5rem",
            64: "16rem",
            72: "18rem",
            74: "18.5rem",
            80: "20rem",
            87: "21.75rem",
            96: "24rem",
            100: "25rem",
            112: "28rem",
            116: "29rem",
            128: "32rem",
            135: "33.75rem",
            148: "37rem",
            160: "40rem",
            170: "42.5rem",
            186: "46.5rem",
            235: "58.75rem",
            470: "117.5rem",
            px: "1px",
            0.5: "0.125rem",
            1.5: "0.375rem",
            2.5: "0.625rem",
            3.5: "0.875rem"
          },
          backgroundColor: theme => ({
            ...theme('colors'),
            body: '#fff',
          }),
          textColor: theme => ({
            ...theme('colors'),
            body: '#1D1F1E',
          }),
          fontFamily: {
            body: [
              "Figtree",
              "ui-sans-serif",
              "system-ui",
              "-apple-system",
              "BlinkMacSystemFont",
              '"Segoe UI"',
              "Roboto",
              '"Helvetica Neue"',
              "Arial",
              '"Noto Sans"',
              "sans-serif",
              '"Apple Color Emoji"',
              '"Segoe UI Emoji"',
              '"Segoe UI Symbol"',
              '"Noto Color Emoji"'
            ],
            heading: [
              "Figtree",
              "ui-sans-serif",
              "system-ui",
              "-apple-system",
              "BlinkMacSystemFont",
              '"Segoe UI"',
              "Roboto",
              '"Helvetica Neue"',
              "Arial",
              '"Noto Sans"',
              "sans-serif",
              '"Apple Color Emoji"',
              '"Segoe UI Emoji"',
              '"Segoe UI Symbol"',
              '"Noto Color Emoji"'
            ],
            sans: [
              "Figtree",
              "DM Sans",
              "ui-sans-serif",
              "system-ui",
              "-apple-system",
              "BlinkMacSystemFont",
              '"Segoe UI"',
              "Roboto",
              '"Helvetica Neue"',
              "Arial",
              '"Noto Sans"',
              "sans-serif",
              '"Apple Color Emoji"',
              '"Segoe UI Emoji"',
              '"Segoe UI Symbol"',
              '"Noto Color Emoji"'
            ]
          },
          fontSize: {
            xs: ["0.75rem", { lineHeight: "1.5" }],
            sm: ["0.875rem", { lineHeight: "1.25" }],
            base: ["1rem", { lineHeight: "1.5" }],
            lg: ["1.125rem", { lineHeight: "1.5" }],
            xl: ["1.25rem", { lineHeight: "1.5" }],
            "2xl": ["1.5rem", { lineHeight: "1.3" }],
            "3xl": ["1.875rem", { lineHeight: "1.3" }],
            "4xl": ["2.25rem", { lineHeight: "1.2" }],
            "5xl": ["3rem", { lineHeight: "0.95" }],
            "6xl": ["3.75rem", { lineHeight: "0.95" }],
            "7xl": ["4.5rem", { lineHeight: "0.95" }],
            "8xl": ["6rem", { lineHeight: "0.95" }],
            "9xl": ["10.75rem", { lineHeight: "1" }],
            "10xl": ["14rem", { lineHeight: "1" }]
          },
          borderRadius: {
            none: "0px",
            sm: "0.125rem",
            DEFAULT: "0.25rem",
            md: "0.375rem",
            lg: "0.5rem",
            xl: "0.75rem",
            "2xl": "1rem",
            "3xl": "1.25rem",
            "4xl": "1.875rem",
            "5xl": "5rem",
            full: "9999px"
          }
        }
      }
    }
  ],
  content: [
    "./src/**/*.{html,js}"
  ],
  safelist: [
    // Add any dynamically generated classes here if needed
  ]
};
